{
 "title": "FVE",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "FVE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 } },
  {
   "title": "PV Power",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "main",
     "query": "SELECT last(\"pvPower\") FROM \"autogen\".\"main\" WHERE time > now() - 1m ORDER BY time DESC",
     "select": [
      [
       { "params": [ "pvPower" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PV Voltage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "main",
     "query": "SELECT last(\"pvInputVoltage\") FROM \"autogen\".\"main\" WHERE time > now() - 1m ORDER BY time DESC",
     "select": [
      [
       { "params": [ "batteryCapacity" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "main",
     "query": "SELECT last(\"batteryCapacity\") FROM \"main\" WHERE time > now() - 1m ORDER BY time DESC",
     "select": [
      [
       { "params": [ "batteryCapacity" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Output Power",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "main",
     "query": "SELECT last(\"outputPowerActive\") FROM \"main\" WHERE time > now() - 1m ORDER BY time DESC",
     "select": [
      [
       { "params": [ "batteryCapacity" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inverter",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 21, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "main",
     "query": "SELECT mean(\"batteryCapacity\") AS \"Battery\", mean(\"pvPower\") AS \"PV Power\", mean(\"outputPowerActive\") AS \"Output Power\", mean(\"batteryChargingCurrent\") AS \"Battery Charging\", mean(\"batteryDischargeCurrent\") AS \"Battery Discharging\", mean(\"pvInputVoltage\") AS \"PV Voltage\" FROM \"autogen\".\"main\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "batteryCapacity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Battery" ], "type": "alias" }
      ],
      [
       { "params": [ "pvPower" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "PV Power" ], "type": "alias" }
      ],
      [
       { "params": [ "outputPowerActive" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Output Power" ], "type": "alias" }
      ],
      [
       { "params": [ "batteryChargingCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Battery Charging" ], "type": "alias" }
      ],
      [
       { "params": [ "batteryDischargeCurrent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Battery Discharging" ], "type": "alias" }
      ],
      [
       { "params": [ "pvInputVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "PV Voltage" ], "type": "alias" }
      ],
      [
       { "params": [ "batteryVoltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Battery Voltage" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}